<div class="field required">
    <!-- <label for="mobile_no" class="label"><span><?php /* @escapeNotVerified */ echo __() ?></span></label> -->
    <div class="control">
        <input type="text" name="mobile_no" id="mobile_no" value="" placeholder="Mobile Number*" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" class="input-text" value=" ?>" data-validate="{required:true}">
    </div>
</div>




